---
title: "Oxygen_gradients"
output: html_notebook
---

# Introduction

This rmd. file imports oxygen data from Google sheet
Data is used to plot a oxygen gradient map of the winogradsky column 

#Loading Packages 

```{r loading packages}
library(tidyverse) 
library(googledrive) 
library(googlesheets4)
#library(ggplot2)
library(knitr)
library(minpack.lm)
library(broom)
```

#Importing from google sheet

```{r load CleanOxygenData direct from googlesheet}

googlesheets4::gs4_deauth()

CleanData_Oxygen <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1hNakCyqPsTNRFpf1lGjoBQ-papyZ6xHKT6mcvh3LMb8/edit?pli=1&gid=842906991#gid=842906991", "CleanData_Oxygen") |>
  mutate(Sample = as.character(Sample))

kable(CleanData_Oxygen) 
```

```{r load CleanVoltageData direct from googlesheet}

googlesheets4::gs4_deauth()

CleanData_Voltage <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1hNakCyqPsTNRFpf1lGjoBQ-papyZ6xHKT6mcvh3LMb8/edit?pli=1&gid=842906991#gid=842906991", "CleanData_Voltage") |>
  mutate(Sample = as.character(Sample))

kable(CleanData_Voltage)
```

Combine O2 & Voltage data by sample & depth
```{r gradients_df}
Gradients <- left_join(x = CleanData_Oxygen, y = CleanData_Voltage, by = c("Sample", "Depth_cm"))
```


#Oxygen Gradient Plot

```{r Oxygen gradients}
ggplot(data = CleanData_Oxygen) +
geom_point(aes(y = DO_µg_L, x = Depth_cm)) + 
  #scale_y_reverse() +
  #labs( title= "Oxygen Gradients", caption= "Figure X. Dissolved Oxygen (DO) (µg/L) measured in four Winogradsky colums at 5 depths (cm)") 
  #+ theme(plot.caption= element_text(size = 11, hjust=0)) +
  #geom_path(aes(y = Depth_cm, x = DO_µg_L)) +
  facet_grid(cols = vars(Sample)) +
  theme_bw()
#+ scale_y_continuous(limits = c(0, 300))
```

```{r decay fits}
#define exponential decay function for data fitting.
exp_decay <- function(x, i, mu){y = i * exp(mu * x)}


O2_nest <- CleanData_Oxygen |>  #alternate forward pipe is %>% loaded with tidyverse
  nest(.by = "Sample") |>
  mutate(DecayFit = purrr::map(data, ~nlsLM(DO_µg_L ~ exp_decay(x = Depth_cm, i, mu),
                                            data = .x)),
         DecayTidy = purrr::map(DecayFit, tidy),
         DecayParam = purrr::map(DecayFit, glance),
         DecayPredict = purrr::map(DecayFit, augment)
         )

 
```


```{r plot O2 decay fits}
O2_nest |>
  unnest(cols = c(DecayPredict)) |>
  ggplot() +
  geom_point(aes(x = Depth_cm, y = DO_µg_L)) +
  geom_line(aes(x = Depth_cm, y = .fitted)) +
  geom_point(aes(x = Depth_cm, y = .resid), colour = "red") +
  facet_grid(cols = vars(unlist(Sample))) +
  theme_bw()
```

```{r show fit parameters}
O2_nest |>
unnest(cols = c(DecayTidy)) |>
 select(-c(data, DecayFit, DecayParam, DecayPredict)) |>
  select(-c(statistic)) |>
  pivot_wider(id_cols = Sample, names_from = term, values_from = c(estimate, std.error, p.value)) |>
  kable()
```
```{r Plotting Voltage Gradients in water at 10 seconds}

ggplot(data = Gradients) +
  geom_point(aes(x = Depth_cm, y = Voltage_Water_10s)) + 
  facet_grid(cols = vars(Sample)) + 
  theme_bw()
```

```{r Plotting With a linear fit}
Gradients %>%
  ggplot() +
 geom_point(aes(x = Depth_cm, y = Voltage_Water_10s)) + 
  geom_smooth(aes( x = Depth_cm, y = Voltage_Water_10s), method = "lm", se=FALSE) +
  #facet_wrap(vars((Sample))) +
facet_grid(cols = vars(Sample)) + 
  theme_bw()
```

